# sector_data.py
# 11 GICS Sectors with top 50 companies each

import os, sys
_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
if _THIS_DIR not in sys.path:
    sys.path.insert(0, _THIS_DIR)

# ─────────────────────────────────────────────────────────────────────────────
# The 11 standard market sectors (GICS classification adapted for India)
# ─────────────────────────────────────────────────────────────────────────────

SECTORS = {
    "1":  "Energy",
    "2":  "Materials",
    "3":  "Industrials",
    "4":  "Consumer Discretionary",
    "5":  "Consumer Staples",
    "6":  "Healthcare",
    "7":  "Financials",
    "8":  "Information Technology",
    "9":  "Communication Services",
    "10": "Utilities",
    "11": "Real Estate",
}

# ─────────────────────────────────────────────────────────────────────────────
# Top 50 companies per sector (NSE symbols)
# Format: {SYMBOL: {name, market_cap_cr, nse_symbol, screener_id}}
# ─────────────────────────────────────────────────────────────────────────────

SECTOR_COMPANIES = {

    # ── 1. ENERGY ─────────────────────────────────────────────────────────────
    "Energy": {
        "RELIANCE"    : {"name": "Reliance Industries",         "cap": 1_750_000, "sub": "Oil & Gas"},
        "ONGC"        : {"name": "Oil & Natural Gas Corp",      "cap": 330_000,   "sub": "Oil & Gas"},
        "BPCL"        : {"name": "Bharat Petroleum Corp",       "cap": 110_000,   "sub": "Oil & Gas"},
        "IOC"         : {"name": "Indian Oil Corporation",      "cap": 190_000,   "sub": "Oil & Gas"},
        "HINDPETRO"   : {"name": "Hindustan Petroleum",         "cap": 55_000,    "sub": "Oil & Gas"},
        "GAIL"        : {"name": "GAIL India",                  "cap": 120_000,   "sub": "Natural Gas"},
        "PETRONET"    : {"name": "Petronet LNG",                "cap": 45_000,    "sub": "Natural Gas"},
        "OIL"         : {"name": "Oil India",                   "cap": 55_000,    "sub": "Oil & Gas"},
        "MGL"         : {"name": "Mahanagar Gas",               "cap": 14_000,    "sub": "Natural Gas"},
        "IGL"         : {"name": "Indraprastha Gas",            "cap": 27_000,    "sub": "Natural Gas"},
        "GSPL"        : {"name": "Gujarat State Petronet",      "cap": 12_000,    "sub": "Natural Gas"},
        "GUJGASLTD"   : {"name": "Gujarat Gas",                 "cap": 18_000,    "sub": "Natural Gas"},
        "AEGASIND"    : {"name": "Aether Industries",           "cap": 8_000,     "sub": "Chemicals"},
        "CASTROLIND"  : {"name": "Castrol India",               "cap": 11_000,    "sub": "Oil & Gas"},
        "MRPL"        : {"name": "MRPL",                        "cap": 13_000,    "sub": "Oil & Gas"},
        "CPCL"        : {"name": "Chennai Petroleum",           "cap": 7_000,     "sub": "Oil & Gas"},
        "HPCL"        : {"name": "HPCL",                        "cap": 55_000,    "sub": "Oil & Gas"},
        "ADANIGREEN"  : {"name": "Adani Green Energy",          "cap": 270_000,   "sub": "Renewable"},
        "ADANIPOWER"  : {"name": "Adani Power",                 "cap": 230_000,   "sub": "Power"},
        "TATAPOWER"   : {"name": "Tata Power",                  "cap": 120_000,   "sub": "Power"},
        "NTPC"        : {"name": "NTPC",                        "cap": 340_000,   "sub": "Power"},
        "POWERGRID"   : {"name": "Power Grid Corp",             "cap": 250_000,   "sub": "Power"},
        "COALINDIA"   : {"name": "Coal India",                  "cap": 230_000,   "sub": "Coal"},
        "NHPC"        : {"name": "NHPC",                        "cap": 80_000,    "sub": "Renewable"},
        "SJVN"        : {"name": "SJVN",                        "cap": 50_000,    "sub": "Renewable"},
        "TORNTPOWER"  : {"name": "Torrent Power",               "cap": 42_000,    "sub": "Power"},
        "CESC"        : {"name": "CESC",                        "cap": 16_000,    "sub": "Power"},
        "RPOWER"      : {"name": "Reliance Power",              "cap": 20_000,    "sub": "Power"},
        "ADANITRANS"  : {"name": "Adani Transmission",          "cap": 85_000,    "sub": "Power"},
        "IREDA"       : {"name": "IREDA",                       "cap": 45_000,    "sub": "Renewable"},
        "SUZLON"      : {"name": "Suzlon Energy",               "cap": 55_000,    "sub": "Renewable"},
        "INOXWIND"    : {"name": "Inox Wind",                   "cap": 14_000,    "sub": "Renewable"},
        "GREENKO"     : {"name": "Greenko Energy",              "cap": 8_000,     "sub": "Renewable"},
        "KEC"         : {"name": "KEC International",           "cap": 30_000,    "sub": "Power"},
        "KALPATPOWR"  : {"name": "Kalpataru Power",             "cap": 19_000,    "sub": "Power"},
        "POWERMECH"   : {"name": "Power Mech Projects",         "cap": 5_500,     "sub": "Power"},
        "ENGINERSIN"  : {"name": "Engineers India",             "cap": 8_000,     "sub": "Oil & Gas"},
        "GUJRATGAS"   : {"name": "Gujarat Gas",                 "cap": 18_000,    "sub": "Natural Gas"},
        "AEGIS"       : {"name": "Aegis Logistics",             "cap": 10_000,    "sub": "Oil & Gas"},
        "PRISTINE"    : {"name": "Pristine Industries",         "cap": 2_000,     "sub": "Oil & Gas"},
        "OCCL"        : {"name": "Oriental Carbon",             "cap": 1_500,     "sub": "Chemicals"},
        "DEEPIND"     : {"name": "Deep Industries",             "cap": 3_000,     "sub": "Oil & Gas"},
        "GANDHAR"     : {"name": "Gandhar Oil",                 "cap": 1_200,     "sub": "Oil & Gas"},
        "SOTL"        : {"name": "Savita Oil Technologies",     "cap": 2_800,     "sub": "Oil & Gas"},
        "SEPC"        : {"name": "SEPC",                        "cap": 1_800,     "sub": "Power"},
        "RTNPOWER"    : {"name": "Ratnagiri Power",             "cap": 900,       "sub": "Power"},
        "JSWENERGY"   : {"name": "JSW Energy",                  "cap": 90_000,    "sub": "Power"},
        "CGPOWER"     : {"name": "CG Power",                    "cap": 55_000,    "sub": "Power"},
        "ABB"         : {"name": "ABB India",                   "cap": 70_000,    "sub": "Power"},
        "SIEMENS"     : {"name": "Siemens India",               "cap": 100_000,   "sub": "Power"},
    },

    # ── 2. MATERIALS ──────────────────────────────────────────────────────────
    "Materials": {
        "TATASTEEL"   : {"name": "Tata Steel",                  "cap": 180_000,   "sub": "Steel"},
        "JSWSTEEL"    : {"name": "JSW Steel",                   "cap": 200_000,   "sub": "Steel"},
        "HINDALCO"    : {"name": "Hindalco Industries",         "cap": 140_000,   "sub": "Aluminium"},
        "VEDL"        : {"name": "Vedanta",                     "cap": 120_000,   "sub": "Diversified Metals"},
        "COALINDIA"   : {"name": "Coal India",                  "cap": 230_000,   "sub": "Coal"},
        "NMDC"        : {"name": "NMDC",                        "cap": 58_000,    "sub": "Iron Ore"},
        "SAIL"        : {"name": "Steel Authority of India",    "cap": 45_000,    "sub": "Steel"},
        "JSWSTEEL"    : {"name": "JSW Steel",                   "cap": 200_000,   "sub": "Steel"},
        "ULTRACEMCO"  : {"name": "UltraTech Cement",            "cap": 300_000,   "sub": "Cement"},
        "GRASIM"      : {"name": "Grasim Industries",           "cap": 150_000,   "sub": "Cement"},
        "AMBUJACEM"   : {"name": "Ambuja Cements",              "cap": 130_000,   "sub": "Cement"},
        "ACC"         : {"name": "ACC",                         "cap": 55_000,    "sub": "Cement"},
        "SHREECEM"    : {"name": "Shree Cement",                "cap": 95_000,    "sub": "Cement"},
        "DALMIACEMT"  : {"name": "Dalmia Bharat",               "cap": 35_000,    "sub": "Cement"},
        "RAMCOCEM"    : {"name": "Ramco Cements",               "cap": 21_000,    "sub": "Cement"},
        "JKCEMENT"    : {"name": "JK Cement",                   "cap": 23_000,    "sub": "Cement"},
        "PIDILITIND"  : {"name": "Pidilite Industries",         "cap": 140_000,   "sub": "Chemicals"},
        "DEEPAKNTR"   : {"name": "Deepak Nitrite",              "cap": 22_000,    "sub": "Chemicals"},
        "SOLARINDS"   : {"name": "Solar Industries",            "cap": 85_000,    "sub": "Chemicals"},
        "AARTI"       : {"name": "Aarti Industries",            "cap": 22_000,    "sub": "Chemicals"},
        "NAVINFLUOR"  : {"name": "Navin Fluorine",              "cap": 14_000,    "sub": "Chemicals"},
        "FINEORG"     : {"name": "Fine Organic",                "cap": 9_500,     "sub": "Chemicals"},
        "PIIND"       : {"name": "PI Industries",               "cap": 55_000,    "sub": "Agrochemicals"},
        "UPL"         : {"name": "UPL",                         "cap": 32_000,    "sub": "Agrochemicals"},
        "RALLIS"      : {"name": "Rallis India",                "cap": 5_500,     "sub": "Agrochemicals"},
        "APLAPOLLO"   : {"name": "APL Apollo Tubes",            "cap": 38_000,    "sub": "Steel"},
        "RATNAMANI"   : {"name": "Ratnamani Metals",            "cap": 17_000,    "sub": "Steel"},
        "WELCORP"     : {"name": "Welspun Corp",                "cap": 11_000,    "sub": "Steel"},
        "JINDALSTEL"  : {"name": "Jindal Steel & Power",        "cap": 65_000,    "sub": "Steel"},
        "JSL"         : {"name": "Jindal Stainless",            "cap": 35_000,    "sub": "Steel"},
        "HINDZINC"    : {"name": "Hindustan Zinc",              "cap": 155_000,   "sub": "Zinc"},
        "NATIONALUM"  : {"name": "National Aluminium",          "cap": 28_000,    "sub": "Aluminium"},
        "MOIL"        : {"name": "MOIL",                        "cap": 8_500,     "sub": "Manganese"},
        "GMRINFRA"    : {"name": "GMR Infrastructure",          "cap": 45_000,    "sub": "Infrastructure"},
        "CLEAN"       : {"name": "Clean Science",               "cap": 8_000,     "sub": "Chemicals"},
        "GALAXY"      : {"name": "Galaxy Surfactants",          "cap": 9_000,     "sub": "Chemicals"},
        "BASF"        : {"name": "BASF India",                  "cap": 13_000,    "sub": "Chemicals"},
        "NOCIL"       : {"name": "NOCIL",                       "cap": 4_500,     "sub": "Chemicals"},
        "ATUL"        : {"name": "Atul",                        "cap": 23_000,    "sub": "Chemicals"},
        "SUDARSCHEM"  : {"name": "Sudarshan Chemical",          "cap": 5_500,     "sub": "Chemicals"},
        "VINATIORGA"  : {"name": "Vinati Organics",             "cap": 17_000,    "sub": "Chemicals"},
        "GHCL"        : {"name": "GHCL",                        "cap": 4_500,     "sub": "Chemicals"},
        "PCBL"        : {"name": "PCBL",                        "cap": 11_000,    "sub": "Carbon Black"},
        "GRAPHITE"    : {"name": "Graphite India",              "cap": 8_000,     "sub": "Carbon"},
        "HEGLTD"      : {"name": "HEG",                         "cap": 9_000,     "sub": "Carbon"},
        "EPIGRAL"     : {"name": "Epigral",                     "cap": 6_000,     "sub": "Chemicals"},
        "ROSSARI"     : {"name": "Rossari Biotech",             "cap": 4_000,     "sub": "Chemicals"},
        "TATACHEM"    : {"name": "Tata Chemicals",              "cap": 28_000,    "sub": "Chemicals"},
        "GSFC"        : {"name": "Gujarat State Fertilizers",   "cap": 7_500,     "sub": "Fertilizers"},
        "GNFC"        : {"name": "GNFC",                        "cap": 8_000,     "sub": "Fertilizers"},
    },

    # ── 3. INDUSTRIALS ────────────────────────────────────────────────────────
    "Industrials": {
        "LT"          : {"name": "Larsen & Toubro",             "cap": 500_000,   "sub": "Engineering"},
        "SIEMENS"     : {"name": "Siemens India",               "cap": 100_000,   "sub": "Engineering"},
        "ABB"         : {"name": "ABB India",                   "cap": 70_000,    "sub": "Engineering"},
        "BHEL"        : {"name": "BHEL",                        "cap": 55_000,    "sub": "Heavy Engineering"},
        "HAL"         : {"name": "Hindustan Aeronautics",       "cap": 280_000,   "sub": "Defence"},
        "BEL"         : {"name": "Bharat Electronics",          "cap": 195_000,   "sub": "Defence"},
        "MAZDOCK"     : {"name": "Mazagon Dock",                "cap": 85_000,    "sub": "Defence"},
        "COCHINSHIP"  : {"name": "Cochin Shipyard",             "cap": 20_000,    "sub": "Shipbuilding"},
        "GRINDWELL"   : {"name": "Grindwell Norton",            "cap": 17_000,    "sub": "Abrasives"},
        "CUMMINSIND"  : {"name": "Cummins India",               "cap": 55_000,    "sub": "Engines"},
        "THERMAX"     : {"name": "Thermax",                     "cap": 40_000,    "sub": "Engineering"},
        "VOLTAS"      : {"name": "Voltas",                      "cap": 30_000,    "sub": "Engineering"},
        "HONAUT"      : {"name": "Honeywell Automation",        "cap": 38_000,    "sub": "Automation"},
        "APARINDS"    : {"name": "Apar Industries",             "cap": 22_000,    "sub": "Cables"},
        "POLYCAB"     : {"name": "Polycab India",               "cap": 85_000,    "sub": "Cables"},
        "HAVELLS"     : {"name": "Havells India",               "cap": 105_000,   "sub": "Electricals"},
        "CGPOWER"     : {"name": "CG Power",                    "cap": 55_000,    "sub": "Electricals"},
        "TIINDIA"     : {"name": "Tube Investments",            "cap": 55_000,    "sub": "Engineering"},
        "SCHAEFFLER"  : {"name": "Schaeffler India",            "cap": 35_000,    "sub": "Bearings"},
        "SKFINDIA"    : {"name": "SKF India",                   "cap": 25_000,    "sub": "Bearings"},
        "TIMKEN"      : {"name": "Timken India",                "cap": 17_000,    "sub": "Bearings"},
        "ELGIEQUIP"   : {"name": "Elgi Equipments",             "cap": 16_000,    "sub": "Compressors"},
        "KIRLOSENG"   : {"name": "Kirloskar Brothers",          "cap": 12_000,    "sub": "Pumps"},
        "RKFORGE"     : {"name": "Ramkrishna Forgings",         "cap": 10_000,    "sub": "Forgings"},
        "HAPPYFORGE"  : {"name": "Happy Forgings",              "cap": 9_000,     "sub": "Forgings"},
        "KALYANIFRG"  : {"name": "Bharat Forge",               "cap": 60_000,    "sub": "Forgings"},
        "TEXRAIL"     : {"name": "Texmaco Rail",                "cap": 7_500,     "sub": "Railways"},
        "RVNL"        : {"name": "Rail Vikas Nigam",            "cap": 90_000,    "sub": "Railways"},
        "IRFC"        : {"name": "IRFC",                        "cap": 195_000,   "sub": "Railways"},
        "IRCON"       : {"name": "Ircon International",         "cap": 23_000,    "sub": "Railways"},
        "NBCC"        : {"name": "NBCC",                        "cap": 22_000,    "sub": "Construction"},
        "NCC"         : {"name": "NCC",                         "cap": 15_000,    "sub": "Construction"},
        "KNR"         : {"name": "KNR Constructions",           "cap": 8_500,     "sub": "Construction"},
        "AHLUWALIA"   : {"name": "Ahluwalia Contracts",         "cap": 7_000,     "sub": "Construction"},
        "PNCINFRA"    : {"name": "PNC Infratech",               "cap": 7_500,     "sub": "Infrastructure"},
        "HGINFRA"     : {"name": "H.G. Infra Engineering",      "cap": 7_000,     "sub": "Infrastructure"},
        "DELHIVERY"   : {"name": "Delhivery",                   "cap": 20_000,    "sub": "Logistics"},
        "BLUEDART"    : {"name": "Blue Dart Express",           "cap": 15_000,    "sub": "Logistics"},
        "GICRE"       : {"name": "General Insurance Corp",      "cap": 50_000,    "sub": "Insurance"},
        "CONCOR"      : {"name": "Container Corp of India",     "cap": 40_000,    "sub": "Logistics"},
        "ADANIPORTS"  : {"name": "Adani Ports & SEZ",           "cap": 280_000,   "sub": "Ports"},
        "ESABINDIA"   : {"name": "ESAB India",                  "cap": 6_500,     "sub": "Welding"},
        "ISGEC"       : {"name": "ISGEC Heavy Engineering",     "cap": 5_000,     "sub": "Engineering"},
        "MFECLTD"     : {"name": "MFE Corporation",             "cap": 2_000,     "sub": "Engineering"},
        "INDIANHUME"  : {"name": "Indian Hume Pipe",            "cap": 1_800,     "sub": "Pipes"},
        "HSCL"        : {"name": "Himadri Specialty Chemical",  "cap": 19_000,    "sub": "Chemicals"},
        "JLHL"        : {"name": "Jupiter Life Line",           "cap": 4_500,     "sub": "Healthcare"},
        "PRINCEPIPE"  : {"name": "Prince Pipes",                "cap": 6_000,     "sub": "Pipes"},
        "ASTRAL"      : {"name": "Astral",                      "cap": 45_000,    "sub": "Pipes"},
        "SUPREMEIND"  : {"name": "Supreme Industries",          "cap": 35_000,    "sub": "Plastics"},
    },

    # ── 4. CONSUMER DISCRETIONARY ─────────────────────────────────────────────
    "Consumer Discretionary": {
        "MARUTI"      : {"name": "Maruti Suzuki",               "cap": 340_000,   "sub": "Automobiles"},
        "TATAMOTORS"  : {"name": "Tata Motors",                 "cap": 290_000,   "sub": "Automobiles"},
        "M&M"         : {"name": "Mahindra & Mahindra",         "cap": 370_000,   "sub": "Automobiles"},
        "BAJAJ-AUTO"  : {"name": "Bajaj Auto",                  "cap": 250_000,   "sub": "Two Wheelers"},
        "HEROMOTOCO"  : {"name": "Hero MotoCorp",               "cap": 100_000,   "sub": "Two Wheelers"},
        "EICHERMOT"   : {"name": "Eicher Motors",               "cap": 110_000,   "sub": "Two Wheelers"},
        "TVSMOTORS"   : {"name": "TVS Motor",                   "cap": 130_000,   "sub": "Two Wheelers"},
        "BALKRISIND"  : {"name": "Balkrishna Industries",       "cap": 45_000,    "sub": "Tyres"},
        "MRF"         : {"name": "MRF",                         "cap": 50_000,    "sub": "Tyres"},
        "APOLLOTYRE"  : {"name": "Apollo Tyres",                "cap": 30_000,    "sub": "Tyres"},
        "CEATLTD"     : {"name": "CEAT",                        "cap": 9_500,     "sub": "Tyres"},
        "TITAN"       : {"name": "Titan Company",               "cap": 280_000,   "sub": "Jewellery"},
        "KALYAN"      : {"name": "Kalyan Jewellers",            "cap": 45_000,    "sub": "Jewellery"},
        "SENCO"       : {"name": "Senco Gold",                  "cap": 8_000,     "sub": "Jewellery"},
        "TRENT"       : {"name": "Trent",                       "cap": 180_000,   "sub": "Retail"},
        "DMART"       : {"name": "D-Mart (Avenue Supermarts)",  "cap": 275_000,   "sub": "Retail"},
        "ZOMATO"      : {"name": "Zomato",                      "cap": 210_000,   "sub": "Food Tech"},
        "SWIGGY"      : {"name": "Swiggy",                      "cap": 85_000,    "sub": "Food Tech"},
        "NYKAA"       : {"name": "Nykaa (FSN E-Commerce)",      "cap": 35_000,    "sub": "E-Commerce"},
        "MEESHO"      : {"name": "Meesho",                      "cap": 20_000,    "sub": "E-Commerce"},
        "JUBLFOOD"    : {"name": "Jubilant Foodworks",          "cap": 17_000,    "sub": "QSR"},
        "DEVYANI"     : {"name": "Devyani International",       "cap": 12_000,    "sub": "QSR"},
        "SAPPHIRE"    : {"name": "Sapphire Foods",              "cap": 6_000,     "sub": "QSR"},
        "WESTLIFE"    : {"name": "Westlife Foodworld",          "cap": 7_000,     "sub": "QSR"},
        "PAGEIND"     : {"name": "Page Industries",             "cap": 40_000,    "sub": "Apparel"},
        "ABFRL"       : {"name": "Aditya Birla Fashion",        "cap": 14_000,    "sub": "Apparel"},
        "ASIANPAINT"  : {"name": "Asian Paints",                "cap": 240_000,   "sub": "Paints"},
        "BERGER"      : {"name": "Berger Paints",               "cap": 55_000,    "sub": "Paints"},
        "AKZOINDIA"   : {"name": "Akzo Nobel India",            "cap": 13_000,    "sub": "Paints"},
        "KANSAINER"   : {"name": "Kansai Nerolac",              "cap": 18_000,    "sub": "Paints"},
        "WHIRLPOOL"   : {"name": "Whirlpool India",             "cap": 9_000,     "sub": "Appliances"},
        "BLUESTAR"    : {"name": "Blue Star",                   "cap": 18_000,    "sub": "Appliances"},
        "AMBER"       : {"name": "Amber Enterprises",           "cap": 9_500,     "sub": "Appliances"},
        "DIXON"       : {"name": "Dixon Technologies",          "cap": 55_000,    "sub": "Electronics"},
        "KAJARIACER"  : {"name": "Kajaria Ceramics",            "cap": 11_000,    "sub": "Tiles"},
        "CERA"        : {"name": "Cera Sanitaryware",           "cap": 9_000,     "sub": "Sanitaryware"},
        "RAYMOND"     : {"name": "Raymond",                     "cap": 10_000,    "sub": "Apparel"},
        "SAFARI"      : {"name": "Safari Industries",           "cap": 10_000,    "sub": "Luggage"},
        "VIP"         : {"name": "VIP Industries",              "cap": 5_000,     "sub": "Luggage"},
        "CAMPUS"      : {"name": "Campus Activewear",           "cap": 4_500,     "sub": "Footwear"},
        "METROBRAND"  : {"name": "Metro Brands",                "cap": 18_000,    "sub": "Footwear"},
        "BATA"        : {"name": "Bata India",                  "cap": 16_000,    "sub": "Footwear"},
        "RELAXO"      : {"name": "Relaxo Footwears",            "cap": 10_000,    "sub": "Footwear"},
        "MAHINDCIE"   : {"name": "Mahindra CIE Automotive",     "cap": 14_000,    "sub": "Auto Parts"},
        "MOTHERSON"   : {"name": "Samvardhana Motherson",       "cap": 80_000,    "sub": "Auto Parts"},
        "BOSCH"       : {"name": "Bosch India",                 "cap": 85_000,    "sub": "Auto Parts"},
        "ZYDUSWELL"   : {"name": "Zydus Wellness",              "cap": 9_000,     "sub": "FMCG"},
        "CROMPTON"    : {"name": "Crompton Greaves Consumer",   "cap": 12_000,    "sub": "Appliances"},
        "ORIENTELEC"  : {"name": "Orient Electric",             "cap": 5_000,     "sub": "Appliances"},
        "SYMNL"       : {"name": "Symphony",                    "cap": 7_000,     "sub": "Appliances"},
    },

    # ── 5. CONSUMER STAPLES ───────────────────────────────────────────────────
    "Consumer Staples": {
        "HINDUNILVR"  : {"name": "Hindustan Unilever",          "cap": 550_000,   "sub": "FMCG"},
        "ITC"         : {"name": "ITC",                         "cap": 530_000,   "sub": "FMCG"},
        "NESTLEIND"   : {"name": "Nestle India",                "cap": 250_000,   "sub": "Food"},
        "BRITANNIA"   : {"name": "Britannia Industries",        "cap": 120_000,   "sub": "Food"},
        "TATACONSUM"  : {"name": "Tata Consumer Products",      "cap": 95_000,    "sub": "FMCG"},
        "DABUR"       : {"name": "Dabur India",                 "cap": 90_000,    "sub": "FMCG"},
        "MARICO"      : {"name": "Marico",                      "cap": 90_000,    "sub": "FMCG"},
        "GODREJCP"    : {"name": "Godrej Consumer Products",    "cap": 95_000,    "sub": "FMCG"},
        "COLPAL"      : {"name": "Colgate-Palmolive India",     "cap": 65_000,    "sub": "Personal Care"},
        "PGHL"        : {"name": "Procter & Gamble Hygiene",    "cap": 40_000,    "sub": "FMCG"},
        "GILLETTE"    : {"name": "Gillette India",              "cap": 22_000,    "sub": "Personal Care"},
        "EMAMILTD"    : {"name": "Emami",                       "cap": 28_000,    "sub": "FMCG"},
        "VBL"         : {"name": "Varun Beverages",             "cap": 130_000,   "sub": "Beverages"},
        "RADICO"      : {"name": "Radico Khaitan",              "cap": 18_000,    "sub": "Beverages"},
        "MCDOWELL-N"  : {"name": "United Spirits",              "cap": 55_000,    "sub": "Beverages"},
        "UBL"         : {"name": "United Breweries",            "cap": 30_000,    "sub": "Beverages"},
        "BIKAJI"      : {"name": "Bikaji Foods",                "cap": 14_000,    "sub": "Snacks"},
        "PATANJALI"   : {"name": "Patanjali Foods",             "cap": 45_000,    "sub": "FMCG"},
        "JYOTHYLAB"   : {"name": "Jyothy Labs",                 "cap": 9_000,     "sub": "FMCG"},
        "BAJAJELEC"   : {"name": "Bajaj Electricals",           "cap": 8_000,     "sub": "Appliances"},
        "ZYDUSWELL"   : {"name": "Zydus Wellness",              "cap": 9_000,     "sub": "FMCG"},
        "HONASA"      : {"name": "Honasa Consumer (Mamaearth)", "cap": 12_000,    "sub": "Personal Care"},
        "DOMS"        : {"name": "DOMS Industries",             "cap": 8_000,     "sub": "Stationery"},
        "FLAIR"       : {"name": "Flair Writing",               "cap": 3_500,     "sub": "Stationery"},
        "GODFRYPHLP"  : {"name": "Godfrey Phillips",            "cap": 18_000,    "sub": "Tobacco"},
        "VST"         : {"name": "VST Industries",              "cap": 5_000,     "sub": "Tobacco"},
        "DODLA"       : {"name": "Dodla Dairy",                 "cap": 3_500,     "sub": "Dairy"},
        "HERITGFOOD"  : {"name": "Heritage Foods",              "cap": 2_800,     "sub": "Dairy"},
        "PARAS"       : {"name": "Paras Dairy",                 "cap": 1_500,     "sub": "Dairy"},
        "KWALITY"     : {"name": "Kwality",                     "cap": 800,       "sub": "Dairy"},
        "PGHH"        : {"name": "P&G Hygiene & Health Care",   "cap": 40_000,    "sub": "FMCG"},
        "KFINTECH"    : {"name": "KFin Technologies",           "cap": 14_000,    "sub": "Fintech"},
        "AGROINDS"    : {"name": "Agro Tech Foods",             "cap": 1_200,     "sub": "Food"},
        "CCHHL"       : {"name": "Coca-Cola India (HCCB)",      "cap": 5_000,     "sub": "Beverages"},
        "PEPSICO"     : {"name": "PepsiCo India Holdings",      "cap": 3_000,     "sub": "Beverages"},
        "APEEJAY"     : {"name": "Apeejay Surrendra Park Hotels","cap": 4_000,    "sub": "Hospitality"},
        "KRBL"        : {"name": "KRBL (India Gate)",           "cap": 7_000,     "sub": "Rice"},
        "LT FOODS"    : {"name": "LT Foods",                    "cap": 7_500,     "sub": "Rice"},
        "ADANITOTAL"  : {"name": "Adani Total Gas",             "cap": 60_000,    "sub": "Natural Gas"},
        "NESLIND"     : {"name": "Nestle India",                "cap": 250_000,   "sub": "Food"},
        "AGROPHOS"    : {"name": "Agro Phos India",             "cap": 400,       "sub": "Fertilizers"},
        "PRABHA"      : {"name": "Prabha Telecom",              "cap": 200,       "sub": "Telecom"},
        "JUBLPHARMA"  : {"name": "Jubilant Pharmova",           "cap": 8_000,     "sub": "Pharma"},
        "HATSUN"      : {"name": "Hatsun Agro Product",         "cap": 13_000,    "sub": "Dairy"},
        "PRICOL"      : {"name": "Pricol",                      "cap": 5_000,     "sub": "Auto Parts"},
        "AVANTIFEED"  : {"name": "Avanti Feeds",                "cap": 6_000,     "sub": "Aquaculture"},
        "WATERBASE"   : {"name": "Waterbase",                   "cap": 1_000,     "sub": "Aquaculture"},
        "APEX"        : {"name": "Apex Frozen Foods",           "cap": 1_200,     "sub": "Aquaculture"},
        "GODREJAGRO"  : {"name": "Godrej Agrovet",              "cap": 7_000,     "sub": "Agri"},
        "RALLIS"      : {"name": "Rallis India",                "cap": 5_500,     "sub": "Agrochemicals"},
    },

    # ── 6. HEALTHCARE ─────────────────────────────────────────────────────────
    "Healthcare": {
        "SUNPHARMA"   : {"name": "Sun Pharmaceutical",          "cap": 430_000,   "sub": "Pharma"},
        "DRREDDY"     : {"name": "Dr. Reddy's Laboratories",    "cap": 100_000,   "sub": "Pharma"},
        "CIPLA"       : {"name": "Cipla",                       "cap": 130_000,   "sub": "Pharma"},
        "DIVISLAB"    : {"name": "Divi's Laboratories",         "cap": 120_000,   "sub": "API"},
        "BIOCON"      : {"name": "Biocon",                      "cap": 40_000,    "sub": "Biopharmaceuticals"},
        "LUPIN"       : {"name": "Lupin",                       "cap": 80_000,    "sub": "Pharma"},
        "TORNTPHARM"  : {"name": "Torrent Pharmaceuticals",     "cap": 90_000,    "sub": "Pharma"},
        "AUROPHARMA"  : {"name": "Aurobindo Pharma",            "cap": 60_000,    "sub": "Pharma"},
        "ZYDUSLIFE"   : {"name": "Zydus Lifesciences",          "cap": 85_000,    "sub": "Pharma"},
        "ALKEM"       : {"name": "Alkem Laboratories",          "cap": 60_000,    "sub": "Pharma"},
        "IPCA"        : {"name": "IPCA Laboratories",           "cap": 35_000,    "sub": "Pharma"},
        "GLAXO"       : {"name": "GSK Pharmaceuticals",         "cap": 18_000,    "sub": "Pharma"},
        "PFIZER"      : {"name": "Pfizer India",                "cap": 15_000,    "sub": "Pharma"},
        "ABBOTINDIA"  : {"name": "Abbott India",                "cap": 35_000,    "sub": "Pharma"},
        "SANOFI"      : {"name": "Sanofi India",                "cap": 10_000,    "sub": "Pharma"},
        "AJANTPHARM"  : {"name": "Ajanta Pharma",               "cap": 20_000,    "sub": "Pharma"},
        "GRANULES"    : {"name": "Granules India",              "cap": 12_000,    "sub": "API"},
        "NATCO"       : {"name": "NATCO Pharma",                "cap": 12_000,    "sub": "Pharma"},
        "LALPATHLAB"  : {"name": "Dr. Lal PathLabs",            "cap": 20_000,    "sub": "Diagnostics"},
        "METROPOLIS"  : {"name": "Metropolis Healthcare",       "cap": 8_000,     "sub": "Diagnostics"},
        "THYROCARE"   : {"name": "Thyrocare Technologies",      "cap": 2_500,     "sub": "Diagnostics"},
        "APOLLOHOSP"  : {"name": "Apollo Hospitals",            "cap": 90_000,    "sub": "Hospitals"},
        "FORTIS"      : {"name": "Fortis Healthcare",           "cap": 30_000,    "sub": "Hospitals"},
        "MAXHEALTH"   : {"name": "Max Healthcare",              "cap": 70_000,    "sub": "Hospitals"},
        "MEDANTA"     : {"name": "Global Health (Medanta)",     "cap": 22_000,    "sub": "Hospitals"},
        "HCG"         : {"name": "Healthcare Global",           "cap": 5_000,     "sub": "Hospitals"},
        "SUVENPHAR"   : {"name": "Suven Pharmaceuticals",       "cap": 13_000,    "sub": "Pharma"},
        "LAURUSLABS"  : {"name": "Laurus Labs",                 "cap": 22_000,    "sub": "API"},
        "SEQUENT"     : {"name": "Sequent Scientific",          "cap": 4_500,     "sub": "Animal Health"},
        "SOLARA"      : {"name": "Solara Active Pharma",        "cap": 3_000,     "sub": "API"},
        "SUDARSCHEM"  : {"name": "Sudarshan Chemical",          "cap": 5_500,     "sub": "Chemicals"},
        "PGHL"        : {"name": "Procter & Gamble Hygiene",    "cap": 40_000,    "sub": "Personal Care"},
        "GLAND"       : {"name": "Gland Pharma",                "cap": 17_000,    "sub": "Pharma"},
        "PPLPHARMA"   : {"name": "Piramal Pharma",              "cap": 14_000,    "sub": "Pharma"},
        "JBLIND"      : {"name": "JB Chemicals",                "cap": 20_000,    "sub": "Pharma"},
        "ERIS"        : {"name": "Eris Lifesciences",           "cap": 10_000,    "sub": "Pharma"},
        "INDOCO"      : {"name": "Indoco Remedies",             "cap": 4_500,     "sub": "Pharma"},
        "CAPLIPOINT"  : {"name": "Caplin Point Laboratories",   "cap": 6_000,     "sub": "Pharma"},
        "CONCORDBIO"  : {"name": "Concord Biotech",             "cap": 10_000,    "sub": "Biotech"},
        "DIVI"        : {"name": "Divi's Laboratories",         "cap": 120_000,   "sub": "API"},
        "KIMS"        : {"name": "Krishna Institute of Med Sci", "cap": 12_000,   "sub": "Hospitals"},
        "RAINBOW"     : {"name": "Rainbow Children's Medicare", "cap": 7_500,     "sub": "Hospitals"},
        "NARAYAN"     : {"name": "Narayana Hrudayalaya",        "cap": 20_000,    "sub": "Hospitals"},
        "SHALBY"      : {"name": "Shalby",                      "cap": 3_000,     "sub": "Hospitals"},
        "NH"          : {"name": "Narayana Hrudayalaya",        "cap": 20_000,    "sub": "Hospitals"},
        "RPGLIFE"     : {"name": "RPG Life Sciences",           "cap": 3_000,     "sub": "Pharma"},
        "MEDPLUS"     : {"name": "Medplus Health Services",     "cap": 7_000,     "sub": "Pharmacy Retail"},
        "OPTIEMUS"    : {"name": "Optiemus Infracom",           "cap": 1_500,     "sub": "Electronics"},
        "IPCALAB"     : {"name": "IPCA Laboratories",           "cap": 35_000,    "sub": "Pharma"},
        "WINDLAS"     : {"name": "Windlas Biotech",             "cap": 1_200,     "sub": "Pharma"},
    },

    # ── 7. FINANCIALS ─────────────────────────────────────────────────────────
    "Financials": {
        "HDFCBANK"    : {"name": "HDFC Bank",                   "cap": 1_350_000, "sub": "Private Banks"},
        "ICICIBANK"   : {"name": "ICICI Bank",                  "cap": 1_000_000, "sub": "Private Banks"},
        "KOTAKBANK"   : {"name": "Kotak Mahindra Bank",         "cap": 400_000,   "sub": "Private Banks"},
        "AXISBANK"    : {"name": "Axis Bank",                   "cap": 380_000,   "sub": "Private Banks"},
        "INDUSINDBK"  : {"name": "IndusInd Bank",               "cap": 95_000,    "sub": "Private Banks"},
        "SBIN"        : {"name": "State Bank of India",         "cap": 830_000,   "sub": "PSU Banks"},
        "PNB"         : {"name": "Punjab National Bank",        "cap": 120_000,   "sub": "PSU Banks"},
        "BANKBARODA"  : {"name": "Bank of Baroda",              "cap": 130_000,   "sub": "PSU Banks"},
        "CANBK"       : {"name": "Canara Bank",                 "cap": 95_000,    "sub": "PSU Banks"},
        "UNIONBANK"   : {"name": "Union Bank of India",         "cap": 85_000,    "sub": "PSU Banks"},
        "IDFCFIRSTB"  : {"name": "IDFC First Bank",             "cap": 38_000,    "sub": "Private Banks"},
        "FEDERALBNK"  : {"name": "Federal Bank",                "cap": 40_000,    "sub": "Private Banks"},
        "BANDHANBNK"  : {"name": "Bandhan Bank",                "cap": 28_000,    "sub": "Private Banks"},
        "AUBANK"      : {"name": "AU Small Finance Bank",       "cap": 32_000,    "sub": "SFB"},
        "EQUITASBNK"  : {"name": "Equitas SFB",                 "cap": 9_000,     "sub": "SFB"},
        "BAJFINANCE"  : {"name": "Bajaj Finance",               "cap": 500_000,   "sub": "NBFC"},
        "BAJAJFINSV"  : {"name": "Bajaj Finserv",               "cap": 280_000,   "sub": "NBFC"},
        "CHOLAFIN"    : {"name": "Cholamandalam Finance",       "cap": 110_000,   "sub": "NBFC"},
        "MUTHOOTFIN"  : {"name": "Muthoot Finance",             "cap": 80_000,    "sub": "NBFC"},
        "LICHSGFIN"   : {"name": "LIC Housing Finance",         "cap": 30_000,    "sub": "Housing Finance"},
        "PNBHOUSING"  : {"name": "PNB Housing Finance",         "cap": 22_000,    "sub": "Housing Finance"},
        "HOMEFIRST"   : {"name": "Home First Finance",          "cap": 8_500,     "sub": "Housing Finance"},
        "MANAPPURAM"  : {"name": "Manappuram Finance",          "cap": 20_000,    "sub": "Gold Loans"},
        "IIFL"        : {"name": "IIFL Finance",                "cap": 16_000,    "sub": "NBFC"},
        "SBICARD"     : {"name": "SBI Cards",                   "cap": 70_000,    "sub": "Credit Cards"},
        "HDFCLIFE"    : {"name": "HDFC Life Insurance",         "cap": 150_000,   "sub": "Life Insurance"},
        "SBILIFE"     : {"name": "SBI Life Insurance",          "cap": 160_000,   "sub": "Life Insurance"},
        "ICICIPRULI"  : {"name": "ICICI Prudential Life",       "cap": 90_000,    "sub": "Life Insurance"},
        "ICICIGI"     : {"name": "ICICI Lombard GIC",           "cap": 75_000,    "sub": "General Insurance"},
        "STARHEALTH"  : {"name": "Star Health Insurance",       "cap": 38_000,    "sub": "Health Insurance"},
        "GODIGIT"     : {"name": "Go Digit Insurance",          "cap": 20_000,    "sub": "General Insurance"},
        "HDFCAMC"     : {"name": "HDFC AMC",                    "cap": 90_000,    "sub": "AMC"},
        "NAM-INDIA"   : {"name": "Nippon India Mutual Fund",    "cap": 38_000,    "sub": "AMC"},
        "ANGELONE"    : {"name": "Angel One",                   "cap": 14_000,    "sub": "Broking"},
        "MOTILALOFS"  : {"name": "Motilal Oswal Financial",     "cap": 35_000,    "sub": "Broking"},
        "NUVAMA"      : {"name": "Nuvama Wealth",               "cap": 18_000,    "sub": "Wealth Mgmt"},
        "360ONE"      : {"name": "360 ONE WAM",                 "cap": 30_000,    "sub": "Wealth Mgmt"},
        "KFINTECH"    : {"name": "KFin Technologies",           "cap": 14_000,    "sub": "Fintech"},
        "CAMS"        : {"name": "Computer Age Management",     "cap": 15_000,    "sub": "Fintech"},
        "PAYTM"       : {"name": "One97 Communications (Paytm)","cap": 40_000,    "sub": "Fintech"},
        "POLICYBZR"   : {"name": "PB Fintech (PolicyBazaar)",   "cap": 45_000,    "sub": "Insurtech"},
        "FINCABLES"   : {"name": "Finolex Cables",              "cap": 14_000,    "sub": "Cables"},
        "APTUS"       : {"name": "Aptus Value Housing",         "cap": 10_000,    "sub": "Housing Finance"},
        "CREDITACC"   : {"name": "CreditAccess Grameen",        "cap": 15_000,    "sub": "MFI"},
        "SPANDANA"    : {"name": "Spandana Sphoorty",           "cap": 7_000,     "sub": "MFI"},
        "FUSION"      : {"name": "Fusion Micro Finance",        "cap": 4_000,     "sub": "MFI"},
        "UJJIVANSFB"  : {"name": "Ujjivan SFB",                 "cap": 8_000,     "sub": "SFB"},
        "ESAFSFB"     : {"name": "ESAF SFB",                    "cap": 4_000,     "sub": "SFB"},
        "UTKARSHBNK"  : {"name": "Utkarsh SFB",                 "cap": 5_000,     "sub": "SFB"},
        "SURYODAY"    : {"name": "Suryoday SFB",                "cap": 2_500,     "sub": "SFB"},
    },

    # ── 8. INFORMATION TECHNOLOGY ─────────────────────────────────────────────
    "Information Technology": {
        "TCS"         : {"name": "Tata Consultancy Services",   "cap": 1_450_000, "sub": "IT Services"},
        "INFY"        : {"name": "Infosys",                     "cap": 780_000,   "sub": "IT Services"},
        "WIPRO"       : {"name": "Wipro",                       "cap": 320_000,   "sub": "IT Services"},
        "HCLTECH"     : {"name": "HCL Technologies",            "cap": 500_000,   "sub": "IT Services"},
        "TECHM"       : {"name": "Tech Mahindra",               "cap": 150_000,   "sub": "IT Services"},
        "LTIM"        : {"name": "LTIMindtree",                 "cap": 170_000,   "sub": "IT Services"},
        "MPHASIS"     : {"name": "Mphasis",                     "cap": 45_000,    "sub": "IT Services"},
        "COFORGE"     : {"name": "Coforge",                     "cap": 40_000,    "sub": "IT Services"},
        "PERSISTENT"  : {"name": "Persistent Systems",          "cap": 80_000,    "sub": "IT Services"},
        "KPITTECH"    : {"name": "KPIT Technologies",           "cap": 40_000,    "sub": "IT Services"},
        "OFSS"        : {"name": "Oracle Financial Services",   "cap": 120_000,   "sub": "IT Products"},
        "TATAELXSI"   : {"name": "Tata Elxsi",                  "cap": 40_000,    "sub": "IT Services"},
        "MASTEK"      : {"name": "Mastek",                      "cap": 8_000,     "sub": "IT Services"},
        "NIIT"        : {"name": "NIIT",                        "cap": 3_500,     "sub": "IT Training"},
        "NEWGEN"      : {"name": "Newgen Software",             "cap": 12_000,    "sub": "SaaS"},
        "ZENSAR"      : {"name": "Zensar Technologies",         "cap": 12_000,    "sub": "IT Services"},
        "CYIENT"      : {"name": "Cyient",                      "cap": 18_000,    "sub": "Engineering Services"},
        "LTTS"        : {"name": "L&T Technology Services",     "cap": 40_000,    "sub": "Engineering Services"},
        "HEXAWARE"    : {"name": "Hexaware Technologies",       "cap": 40_000,    "sub": "IT Services"},
        "BIRLASOFT"   : {"name": "Birlasoft",                   "cap": 16_000,    "sub": "IT Services"},
        "RSYSTEMS"    : {"name": "R Systems International",     "cap": 5_000,     "sub": "IT Services"},
        "SONATSOFTW"  : {"name": "Sonata Software",             "cap": 8_000,     "sub": "IT Services"},
        "INTELLECT"   : {"name": "Intellect Design Arena",      "cap": 10_000,    "sub": "Fintech"},
        "NUCLEUS"     : {"name": "Nucleus Software",            "cap": 4_500,     "sub": "Fintech"},
        "SAKSOFT"     : {"name": "Saksoft",                     "cap": 1_200,     "sub": "IT Services"},
        "LATENTVIEW"  : {"name": "LatentView Analytics",        "cap": 6_000,     "sub": "Analytics"},
        "DATAMATICS"  : {"name": "Datamatics Global Services",  "cap": 3_500,     "sub": "IT Services"},
        "RATEGAIN"    : {"name": "RateGain Travel Technologies", "cap": 8_000,    "sub": "SaaS"},
        "TANLA"       : {"name": "Tanla Platforms",             "cap": 8_000,     "sub": "CPaaS"},
        "AFFLE"       : {"name": "Affle India",                 "cap": 9_000,     "sub": "AdTech"},
        "INOXGREEN"   : {"name": "Inox Green Energy",           "cap": 3_500,     "sub": "Renewable Tech"},
        "NAUKRI"      : {"name": "Info Edge (Naukri)",          "cap": 85_000,    "sub": "Internet"},
        "JUSTDIAL"    : {"name": "Just Dial",                   "cap": 8_000,     "sub": "Internet"},
        "CARTRADE"    : {"name": "CarTrade Tech",               "cap": 3_500,     "sub": "Internet"},
        "POLICYBZR"   : {"name": "PB Fintech",                  "cap": 45_000,    "sub": "Insurtech"},
        "MAPMYINDIA"  : {"name": "C.E. Info Systems (MapmyIndia)","cap": 12_000, "sub": "GIS"},
        "CDSL"        : {"name": "CDSL",                        "cap": 22_000,    "sub": "Capital Markets"},
        "BSE"         : {"name": "BSE",                         "cap": 30_000,    "sub": "Exchanges"},
        "MCX"         : {"name": "MCX India",                   "cap": 13_000,    "sub": "Exchanges"},
        "INDIGRID"    : {"name": "IndiGrid InvIT",              "cap": 12_000,    "sub": "Infrastructure"},
        "TTML"        : {"name": "Tata Teleservices Maharashtra","cap": 5_000,    "sub": "Telecom"},
        "SUBEX"       : {"name": "Subex",                       "cap": 1_200,     "sub": "Telecom Tech"},
        "OPTIEMUS"    : {"name": "Optiemus Infracom",           "cap": 1_500,     "sub": "Electronics"},
        "ACCELYA"     : {"name": "Accelya Solutions",           "cap": 3_500,     "sub": "Aviation Tech"},
        "SIS"         : {"name": "SIS",                         "cap": 5_000,     "sub": "Security"},
        "QUESS"       : {"name": "Quess Corp",                  "cap": 6_000,     "sub": "Staffing"},
        "TEAMLEASE"   : {"name": "TeamLease Services",          "cap": 4_500,     "sub": "Staffing"},
        "XCHANGING"   : {"name": "Xchanging Solutions",         "cap": 800,       "sub": "IT Services"},
        "EXPLEO"      : {"name": "Expleo Solutions",            "cap": 1_500,     "sub": "Engineering Services"},
        "MSTC"        : {"name": "MSTC",                        "cap": 3_000,     "sub": "E-Commerce"},
    },

    # ── 9. COMMUNICATION SERVICES ─────────────────────────────────────────────
    "Communication Services": {
        "BHARTIARTL"  : {"name": "Bharti Airtel",               "cap": 950_000,   "sub": "Telecom"},
        "RELIANCE"    : {"name": "Reliance (Jio)",              "cap": 1_750_000, "sub": "Telecom"},
        "IDEA"        : {"name": "Vodafone Idea",               "cap": 35_000,    "sub": "Telecom"},
        "TATACOMM"    : {"name": "Tata Communications",         "cap": 38_000,    "sub": "Telecom"},
        "HFCL"        : {"name": "HFCL",                        "cap": 7_500,     "sub": "Telecom Infra"},
        "STLTECH"     : {"name": "STL (Sterlite Technologies)", "cap": 6_500,     "sub": "Optical Fibre"},
        "INDUSTOWER"  : {"name": "Indus Towers",                "cap": 70_000,    "sub": "Telecom Towers"},
        "BSNL"        : {"name": "BSNL",                        "cap": 0,         "sub": "Telecom"},
        "RAILTEL"     : {"name": "RailTel Corporation",         "cap": 6_000,     "sub": "Telecom"},
        "MTNL"        : {"name": "MTNL",                        "cap": 2_000,     "sub": "Telecom"},
        "NAUKRI"      : {"name": "Info Edge",                   "cap": 85_000,    "sub": "Internet"},
        "ZOMATO"      : {"name": "Zomato",                      "cap": 210_000,   "sub": "Food Tech"},
        "SWIGGY"      : {"name": "Swiggy",                      "cap": 85_000,    "sub": "Food Tech"},
        "NYKAA"       : {"name": "Nykaa",                       "cap": 35_000,    "sub": "E-Commerce"},
        "PVR"         : {"name": "PVR Inox",                    "cap": 11_000,    "sub": "Media & Entertainment"},
        "ZEEL"        : {"name": "Zee Entertainment",           "cap": 15_000,    "sub": "Media"},
        "SUNTVNET"    : {"name": "Sun TV Network",              "cap": 25_000,    "sub": "Media"},
        "NETWORK18"   : {"name": "Network18",                   "cap": 12_000,    "sub": "Media"},
        "TV18BRDCST"  : {"name": "TV18 Broadcast",              "cap": 5_000,     "sub": "Media"},
        "RADIOCITY"   : {"name": "Music Broadcast",             "cap": 1_000,     "sub": "Radio"},
        "SAREGAMA"    : {"name": "Saregama India",              "cap": 8_000,     "sub": "Music"},
        "TIPS"        : {"name": "Tips Films",                  "cap": 1_800,     "sub": "Music"},
        "INOXLEISUR"  : {"name": "Inox Leisure",                "cap": 6_000,     "sub": "Entertainment"},
        "NAZARA"      : {"name": "Nazara Technologies",         "cap": 4_000,     "sub": "Gaming"},
        "DELTACORP"   : {"name": "Delta Corp",                  "cap": 3_500,     "sub": "Gaming"},
        "TANLA"       : {"name": "Tanla Platforms",             "cap": 8_000,     "sub": "CPaaS"},
        "ROUTE"       : {"name": "Route Mobile",                "cap": 5_500,     "sub": "CPaaS"},
        "DISH"        : {"name": "Dish TV India",               "cap": 3_000,     "sub": "DTH"},
        "TATASKY"     : {"name": "Tata Play",                   "cap": 0,         "sub": "DTH"},
        "D2H"         : {"name": "Videocon D2H",                "cap": 2_000,     "sub": "DTH"},
        "JAGRAN"      : {"name": "Jagran Prakashan",            "cap": 1_500,     "sub": "Print Media"},
        "DBCORP"      : {"name": "DB Corp",                     "cap": 2_200,     "sub": "Print Media"},
        "HMVL"        : {"name": "Hindustan Media Ventures",    "cap": 700,       "sub": "Print Media"},
        "BALAJITELE"  : {"name": "Balaji Telefilms",            "cap": 1_200,     "sub": "Content"},
        "EROSMEDIA"   : {"name": "Eros International",          "cap": 500,       "sub": "Content"},
        "SHEMAROO"    : {"name": "Shemaroo Entertainment",      "cap": 700,       "sub": "Content"},
        "PRIMEFOCUS"  : {"name": "Prime Focus",                 "cap": 3_000,     "sub": "Content"},
        "NDTV"        : {"name": "NDTV",                        "cap": 6_000,     "sub": "News Media"},
        "TVTODAY"     : {"name": "TV Today Network",            "cap": 1_200,     "sub": "News Media"},
        "NEWSLAUNDRY" : {"name": "Newslaundry",                 "cap": 0,         "sub": "Digital Media"},
        "BRIGHTCOM"   : {"name": "Brightcom Group",             "cap": 2_000,     "sub": "AdTech"},
        "AFFLE"       : {"name": "Affle India",                 "cap": 9_000,     "sub": "AdTech"},
        "VERTOZ"      : {"name": "Vertoz Advertising",          "cap": 1_000,     "sub": "AdTech"},
        "PLACEMENTS"  : {"name": "Placement.Ltd",               "cap": 500,       "sub": "Staffing"},
        "SUBEX"       : {"name": "Subex",                       "cap": 1_200,     "sub": "Telecom Tech"},
        "ONMOBILE"    : {"name": "OnMobile Global",             "cap": 800,       "sub": "Telecom VAS"},
        "TTML"        : {"name": "Tata Teleservices Maharashtra","cap": 5_000,    "sub": "Telecom"},
        "GTLINFRA"    : {"name": "GTL Infrastructure",          "cap": 3_000,     "sub": "Telecom Towers"},
        "BHARATNET"   : {"name": "Bharat Net",                  "cap": 0,         "sub": "Telecom Infra"},
        "RCIL"        : {"name": "Reliance Communications",     "cap": 0,         "sub": "Telecom"},
    },

    # ── 10. UTILITIES ─────────────────────────────────────────────────────────
    "Utilities": {
        "NTPC"        : {"name": "NTPC",                        "cap": 340_000,   "sub": "Power Generation"},
        "POWERGRID"   : {"name": "Power Grid Corp",             "cap": 250_000,   "sub": "Power Transmission"},
        "ADANIGREEN"  : {"name": "Adani Green Energy",          "cap": 270_000,   "sub": "Renewable"},
        "TATAPOWER"   : {"name": "Tata Power",                  "cap": 120_000,   "sub": "Power"},
        "ADANIPOWER"  : {"name": "Adani Power",                 "cap": 230_000,   "sub": "Power"},
        "NHPC"        : {"name": "NHPC",                        "cap": 80_000,    "sub": "Hydro Power"},
        "SJVN"        : {"name": "SJVN",                        "cap": 50_000,    "sub": "Hydro Power"},
        "TORNTPOWER"  : {"name": "Torrent Power",               "cap": 42_000,    "sub": "Power"},
        "CESC"        : {"name": "CESC",                        "cap": 16_000,    "sub": "Power"},
        "JSWENERGY"   : {"name": "JSW Energy",                  "cap": 90_000,    "sub": "Power"},
        "ADANITRANS"  : {"name": "Adani Transmission",          "cap": 85_000,    "sub": "Power Transmission"},
        "IREDA"       : {"name": "IREDA",                       "cap": 45_000,    "sub": "Renewable Finance"},
        "SUZLON"      : {"name": "Suzlon Energy",               "cap": 55_000,    "sub": "Wind Energy"},
        "INOXWIND"    : {"name": "Inox Wind",                   "cap": 14_000,    "sub": "Wind Energy"},
        "RPOWER"      : {"name": "Reliance Power",              "cap": 20_000,    "sub": "Power"},
        "CGPOWER"     : {"name": "CG Power & Industrial",       "cap": 55_000,    "sub": "Power Equipment"},
        "ABB"         : {"name": "ABB India",                   "cap": 70_000,    "sub": "Power Equipment"},
        "BHEL"        : {"name": "BHEL",                        "cap": 55_000,    "sub": "Power Equipment"},
        "KALPATPOWR"  : {"name": "Kalpataru Power",             "cap": 19_000,    "sub": "Power Infra"},
        "KEC"         : {"name": "KEC International",           "cap": 30_000,    "sub": "Power Infra"},
        "GENUSPOWER"  : {"name": "Genus Power Infrastructure",  "cap": 8_000,     "sub": "Smart Metering"},
        "HPL"         : {"name": "HPL Electric & Power",        "cap": 3_000,     "sub": "Metering"},
        "IEXIND"      : {"name": "Indian Energy Exchange",      "cap": 12_000,    "sub": "Power Exchange"},
        "PXIL"        : {"name": "Power Exchange India",        "cap": 2_000,     "sub": "Power Exchange"},
        "MPOWER"      : {"name": "M Power Technologies",        "cap": 500,       "sub": "Smart Grid"},
        "POWERINDIA"  : {"name": "Hitachi Energy India",        "cap": 18_000,    "sub": "Power Equipment"},
        "JYOTISTRUC"  : {"name": "Jyoti Structures",            "cap": 2_000,     "sub": "Power Infra"},
        "ENPRO"       : {"name": "Enpro India",                 "cap": 800,       "sub": "Power"},
        "GUJRATGAS"   : {"name": "Gujarat Gas",                 "cap": 18_000,    "sub": "Gas Distribution"},
        "IGL"         : {"name": "Indraprastha Gas",            "cap": 27_000,    "sub": "Gas Distribution"},
        "MGL"         : {"name": "Mahanagar Gas",               "cap": 14_000,    "sub": "Gas Distribution"},
        "ADFFOODS"    : {"name": "ADF Foods",                   "cap": 2_000,     "sub": "Utilities"},
        "WABCO"       : {"name": "Wabco India",                 "cap": 12_000,    "sub": "Auto Components"},
        "POWERMECH"   : {"name": "Power Mech Projects",         "cap": 5_500,     "sub": "Power O&M"},
        "SEPC"        : {"name": "SEPC",                        "cap": 1_800,     "sub": "Power"},
        "SMLISUZU"    : {"name": "SML Isuzu",                   "cap": 2_500,     "sub": "Vehicles"},
        "GREENPLY"    : {"name": "Greenply Industries",         "cap": 4_000,     "sub": "Plywood"},
        "UGAR"        : {"name": "Ugar Sugar Works",            "cap": 1_000,     "sub": "Sugar"},
        "HARIOMPIPE"  : {"name": "Hariom Pipe Industries",      "cap": 1_500,     "sub": "Pipes"},
        "BOMDYEING"   : {"name": "Bombay Dyeing",               "cap": 3_500,     "sub": "Textiles"},
        "STEELXIND"   : {"name": "Steel Exchange India",        "cap": 1_800,     "sub": "Steel"},
        "BURNPUR"     : {"name": "Burnpur Cement",              "cap": 300,       "sub": "Cement"},
        "RAJESHEXPO"  : {"name": "Rajesh Exports",              "cap": 8_000,     "sub": "Gold Refining"},
        "NAVA"        : {"name": "Nava",                        "cap": 4_500,     "sub": "Power"},
        "ORIENTGRN"   : {"name": "Orient Green Power",          "cap": 1_500,     "sub": "Renewable"},
        "GREENENERGY" : {"name": "Green Energy International",  "cap": 500,       "sub": "Renewable"},
        "WEBSOL"      : {"name": "Websol Energy System",        "cap": 2_500,     "sub": "Solar"},
        "WAAREE"      : {"name": "Waaree Energies",             "cap": 30_000,    "sub": "Solar"},
        "PREMIER"     : {"name": "Premier Energies",            "cap": 15_000,    "sub": "Solar"},
        "SOLEX"       : {"name": "Solex Energy",                "cap": 2_000,     "sub": "Solar"},
    },

    # ── 11. REAL ESTATE ───────────────────────────────────────────────────────
    "Real Estate": {
        "DLF"         : {"name": "DLF",                         "cap": 200_000,   "sub": "Residential"},
        "GODREJPROP"  : {"name": "Godrej Properties",           "cap": 65_000,    "sub": "Residential"},
        "OBEROIRLTY"  : {"name": "Oberoi Realty",               "cap": 45_000,    "sub": "Residential"},
        "PRESTIGE"    : {"name": "Prestige Estates",            "cap": 40_000,    "sub": "Mixed"},
        "BRIGADE"     : {"name": "Brigade Enterprises",         "cap": 25_000,    "sub": "Mixed"},
        "SOBHA"       : {"name": "Sobha",                       "cap": 12_000,    "sub": "Residential"},
        "MAHLIFE"     : {"name": "Mahindra Lifespace",          "cap": 8_000,     "sub": "Residential"},
        "KOLTEPATIL"  : {"name": "Kolte-Patil Developers",      "cap": 4_000,     "sub": "Residential"},
        "SIGNATURE"   : {"name": "Signatureglobal India",       "cap": 9_000,     "sub": "Affordable Housing"},
        "KEYSTONE"    : {"name": "Keystone Realtors",           "cap": 5_000,     "sub": "Residential"},
        "ARVSMART"    : {"name": "Arvind SmartSpaces",          "cap": 3_500,     "sub": "Residential"},
        "ANANTRAJ"    : {"name": "Anant Raj",                   "cap": 12_000,    "sub": "Commercial"},
        "PHOENIXLTD"  : {"name": "Phoenix Mills",               "cap": 55_000,    "sub": "Retail/Commercial"},
        "NEXUSMALLS"  : {"name": "Nexus Select Trust (REIT)",   "cap": 18_000,    "sub": "Retail REIT"},
        "EMBASSY"     : {"name": "Embassy Office Parks REIT",   "cap": 30_000,    "sub": "Office REIT"},
        "MINDSPACEREIT": {"name": "Mindspace REIT",             "cap": 18_000,    "sub": "Office REIT"},
        "BROOKFIELD"  : {"name": "Brookfield India REIT",       "cap": 8_000,     "sub": "Office REIT"},
        "NIFTYBEES"   : {"name": "Nippon India ETF Nifty BeES", "cap": 0,         "sub": "ETF"},
        "INDIGRID"    : {"name": "IndiGrid InvIT",              "cap": 12_000,    "sub": "Power InvIT"},
        "POWERGRIDINV": {"name": "PowerGrid InvIT",             "cap": 6_000,     "sub": "Power InvIT"},
        "IREALTY"     : {"name": "India Realty Fund",           "cap": 0,         "sub": "Real Estate Fund"},
        "ARVIND"      : {"name": "Arvind",                      "cap": 9_000,     "sub": "Textiles/Real Estate"},
        "MAHINDCIE"   : {"name": "Mahindra CIE",                "cap": 14_000,    "sub": "Auto/Real Estate"},
        "IBREALEST"   : {"name": "Indiabulls Real Estate",      "cap": 5_000,     "sub": "Residential"},
        "RUSTOMJEE"   : {"name": "Keystone (Rustomjee)",        "cap": 5_000,     "sub": "Residential"},
        "TRITURBINE"  : {"name": "Triveni Turbine",             "cap": 14_000,    "sub": "Industrial"},
        "TREEHOUSE"   : {"name": "Treehouse Education",         "cap": 200,       "sub": "Education"},
        "GREENPANEL"  : {"name": "Greenpanel Industries",       "cap": 4_000,     "sub": "Wood Panels"},
        "CENTURYPLY"  : {"name": "Century Plyboards",           "cap": 12_000,    "sub": "Plywood"},
        "ARCHIDPLY"   : {"name": "Archidply Industries",        "cap": 500,       "sub": "Plywood"},
        "ASTERDM"     : {"name": "Aster DM Healthcare",         "cap": 18_000,    "sub": "Healthcare"},
        "MEDIASSIST"  : {"name": "Medi Assist Healthcare",      "cap": 3_000,     "sub": "Health Insurance TPA"},
        "CAPACITE"    : {"name": "Capacit'e Infraprojects",     "cap": 3_000,     "sub": "Construction"},
        "ASHOKA"      : {"name": "Ashoka Buildcon",             "cap": 5_000,     "sub": "Roads"},
        "SADBHAV"     : {"name": "Sadbhav Engineering",         "cap": 1_500,     "sub": "Infrastructure"},
        "WELSPUNLIV"  : {"name": "Welspun Living",              "cap": 9_000,     "sub": "Home Textiles"},
        "TRIDENT"     : {"name": "Trident",                     "cap": 15_000,    "sub": "Textiles"},
        "SPORTKING"   : {"name": "Sportking India",             "cap": 1_500,     "sub": "Textiles"},
        "INDHOTEL"    : {"name": "Indian Hotels (Taj)",         "cap": 80_000,    "sub": "Hospitality"},
        "LEMON"       : {"name": "Lemon Tree Hotels",           "cap": 10_000,    "sub": "Hospitality"},
        "CHALET"      : {"name": "Chalet Hotels",               "cap": 8_500,     "sub": "Hospitality"},
        "MAHINDRA"    : {"name": "Mahindra Holidays",           "cap": 7_500,     "sub": "Hospitality"},
        "THOMASCOOK"  : {"name": "Thomas Cook India",           "cap": 5_000,     "sub": "Travel"},
        "IXIGO"       : {"name": "Le Travenues Technology (ixigo)", "cap": 8_000, "sub": "Travel Tech"},
        "EASETRIP"    : {"name": "Easy Trip Planners (EaseMyTrip)", "cap": 3_500, "sub": "Travel Tech"},
        "SAPPHIRE"    : {"name": "Sapphire Foods",              "cap": 6_000,     "sub": "QSR"},
        "ISGEC"       : {"name": "ISGEC Heavy Engineering",     "cap": 5_000,     "sub": "Engineering"},
        "ADANIestates": {"name": "Adani Realty",                "cap": 0,         "sub": "Real Estate"},
        "NESCO"       : {"name": "NESCO",                       "cap": 6_500,     "sub": "Exhibition/IT Park"},
        "MHRIL"       : {"name": "Mahindra Holidays & Resorts", "cap": 7_500,     "sub": "Hospitality"},
    },
}

# ─────────────────────────────────────────────────────────────────────────────
# Benchmarks for 13 metrics
# ─────────────────────────────────────────────────────────────────────────────

METRIC_BENCHMARKS = {
    "Revenue Growth (%)": {
        "excellent": 20, "good": 10, "average": 5, "poor": 0,
        "unit": "%", "higher_is_better": True,
        "description": "YoY Sales Growth", "category": "Growth",
    },
    "EBITDA (Cr)": {
        "excellent": None, "good": None, "average": None, "poor": 0,
        "unit": "₹ Cr", "higher_is_better": True,
        "description": "Operating Profit (EBIT + D&A)", "category": "Profitability",
    },
    "EBITDA Margin (%)": {
        "excellent": 25, "good": 15, "average": 8, "poor": 0,
        "unit": "%", "higher_is_better": True,
        "description": "EBITDA / Revenue × 100", "category": "Profitability",
    },
    "Net Profit / PAT (Cr)": {
        "excellent": None, "good": None, "average": None, "poor": 0,
        "unit": "₹ Cr", "higher_is_better": True,
        "description": "Profit After Tax", "category": "Profitability",
    },
    "PAT Margin (%)": {
        "excellent": 20, "good": 10, "average": 5, "poor": 0,
        "unit": "%", "higher_is_better": True,
        "description": "PAT / Revenue × 100", "category": "Profitability",
    },
    "ROE (%)": {
        "excellent": 25, "good": 15, "average": 10, "poor": 0,
        "unit": "%", "higher_is_better": True,
        "description": "Net Profit / Shareholders Equity", "category": "Returns",
    },
    "ROCE (%)": {
        "excellent": 20, "good": 12, "average": 8, "poor": 0,
        "unit": "%", "higher_is_better": True,
        "description": "EBIT / Capital Employed", "category": "Returns",
    },
    "ROA (%)": {
        "excellent": 10, "good": 5, "average": 2, "poor": 0,
        "unit": "%", "higher_is_better": True,
        "description": "Net Profit / Total Assets", "category": "Returns",
    },
    "EPS (₹)": {
        "excellent": None, "good": None, "average": None, "poor": 0,
        "unit": "₹", "higher_is_better": True,
        "description": "Earnings Per Share", "category": "Valuation",
    },
    "P/E Ratio": {
        "excellent": None, "good": None, "average": None, "poor": None,
        "unit": "x", "higher_is_better": False,
        "description": "Price / EPS (compare to sector)", "category": "Valuation",
    },
    "Debt to Equity": {
        "excellent": 0.3, "good": 0.5, "average": 1.0, "poor": 2.0,
        "unit": "x", "higher_is_better": False,
        "description": "Total Debt / Equity (< 1 safe)", "category": "Financial Health",
    },
    "Current Ratio": {
        "excellent": 2.5, "good": 1.5, "average": 1.0, "poor": 0.5,
        "unit": "x", "higher_is_better": True,
        "description": "Current Assets / Current Liabilities", "category": "Liquidity",
    },
    "Free Cash Flow (Cr)": {
        "excellent": None, "good": None, "average": None, "poor": 0,
        "unit": "₹ Cr", "higher_is_better": True,
        "description": "Operating CF - Capex", "category": "Cash Flow",
    },
}

# Sector-specific P/E benchmarks
SECTOR_PE_BENCHMARKS = {
    "Information Technology" : {"fair": 25, "expensive": 35},
    "Financials"             : {"fair": 15, "expensive": 25},
    "Healthcare"             : {"fair": 30, "expensive": 45},
    "Consumer Staples"       : {"fair": 40, "expensive": 60},
    "Consumer Discretionary" : {"fair": 35, "expensive": 55},
    "Energy"                 : {"fair": 12, "expensive": 20},
    "Materials"              : {"fair": 15, "expensive": 25},
    "Industrials"            : {"fair": 20, "expensive": 35},
    "Utilities"              : {"fair": 15, "expensive": 25},
    "Real Estate"            : {"fair": 20, "expensive": 40},
    "Communication Services" : {"fair": 25, "expensive": 40},
}


def get_sector_companies(sector: str, top_n: int = 50) -> dict:
    """Get top N companies for a sector sorted by market cap."""
    cos = SECTOR_COMPANIES.get(sector, {})
    sorted_cos = dict(
        sorted(cos.items(), key=lambda x: x[1].get("cap", 0), reverse=True)[:top_n]
    )
    return sorted_cos


def get_sector_list() -> list:
    return list(SECTORS.values())


def filter_by_price(companies: dict, prices: dict,
                    mode: str, value=None,
                    min_price: float = None,
                    max_price: float = None) -> dict:
    """
    Filter companies by price.
    mode: 'top_high' | 'top_low' | 'range' | 'top_n_high' | 'top_n_low'
    """
    priced = {
        sym: {**info, "_price": prices.get(sym, 0)}
        for sym, info in companies.items()
        if prices.get(sym, 0) > 0
    }

    if mode == "top_high":
        n = value or 50
        return dict(sorted(priced.items(),
                            key=lambda x: x[1]["_price"],
                            reverse=True)[:n])
    elif mode == "top_low":
        n = value or 50
        return dict(sorted(priced.items(),
                            key=lambda x: x[1]["_price"])[:n])
    elif mode == "range":
        return {
            sym: info for sym, info in priced.items()
            if (min_price or 0) <= info["_price"] <= (max_price or float("inf"))
        }
    return priced